name: Deploy UmaCore Bot to Raspberry Pi

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          printf '%s\n' \
            'DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}' \
            'CHANNEL_ID=${{ secrets.CHANNEL_ID }}' \
            'DATABASE_URL=${{ secrets.DATABASE_URL }}' \
            'LOG_LEVEL=${{ secrets.LOG_LEVEL }}' > .env

      - name: Stop existing containers
        run: docker compose down || true

      - name: Build and deploy Docker containers
        run: docker compose up -d --build
